#!/bin/bash
# build --- Build the project

set -e
TOOLS_DIR="$(unset CDPATH; cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
source $TOOLS_DIR/use

cd $PROJ_DIR

rm -rf public
mkdir -p public/scripts

process-dictionary.mjs

tsc

tree public
